import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./_components/Nav/Nav";
import Footer from "./_components/Footer";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icon: '/img/pa-crest-white-120w.png',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[url(https://3djungle.net/upload/resize_cache/iblock/2ef/400_400_1/2efbde5eea73f55b444881939137a941.jpg)] grid grid-rows-[auto_1fr_auto] min-h-screen">
        <Nav />
        <div>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
